// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk8gYwwyS0O0MmnkvQ_Kn37KBbWYwrwKU',
    appId: '1:1088389283542:web:fc66300be001ef50d05377',
    messagingSenderId: '1088389283542',
    projectId: 'expense-tracker-be6c1',
    authDomain: 'expense-tracker-be6c1.firebaseapp.com',
    storageBucket: 'expense-tracker-be6c1.firebasestorage.app',
    measurementId: 'G-65G1741E9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQw2yLnvn4WuIhcM2qR-z20W2eK087i-Y',
    appId: '1:1088389283542:android:ea015a4feb85341ad05377',
    messagingSenderId: '1088389283542',
    projectId: 'expense-tracker-be6c1',
    storageBucket: 'expense-tracker-be6c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4jEYKWrU12IgFNPhcpg0OiEw6FMwWzLs',
    appId: '1:1088389283542:ios:c20d99531b50abb9d05377',
    messagingSenderId: '1088389283542',
    projectId: 'expense-tracker-be6c1',
    storageBucket: 'expense-tracker-be6c1.firebasestorage.app',
    iosBundleId: 'com.example.appExpensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4jEYKWrU12IgFNPhcpg0OiEw6FMwWzLs',
    appId: '1:1088389283542:ios:c20d99531b50abb9d05377',
    messagingSenderId: '1088389283542',
    projectId: 'expense-tracker-be6c1',
    storageBucket: 'expense-tracker-be6c1.firebasestorage.app',
    iosBundleId: 'com.example.appExpensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk8gYwwyS0O0MmnkvQ_Kn37KBbWYwrwKU',
    appId: '1:1088389283542:web:6ca4cf046140350fd05377',
    messagingSenderId: '1088389283542',
    projectId: 'expense-tracker-be6c1',
    authDomain: 'expense-tracker-be6c1.firebaseapp.com',
    storageBucket: 'expense-tracker-be6c1.firebasestorage.app',
    measurementId: 'G-1KD2Y3JCKJ',
  );
}
